'use strict';

// Tests for scripts/build_userscripts.py's @include marker guard.
//
// Why the guard exists: INCLUDE_RE.sub never asserted a match, so a .src.js
// that lost its `/* @include admincom-common.js */` marker built clean, passed
// node --check (the syntax is valid; the references are not), reported "up to
// date", and then threw ReferenceError in the browser on first use -- because
// dbg/fetchWithRetry and the rest were silently never inlined. Merging to
// master is the deploy for this repo, so that reached every admin.
//
// See tests/helpers/build-script-runner.js for the fixture/spawn harness and
// why these tests run a process.

const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { PYTHON, makeFixture, runBuild } = require('./helpers/build-script-runner');

test('build_userscripts.py @include marker guard', { skip: PYTHON ? false : 'no python on PATH' }, async (t) => {
  await t.test('a source with its marker builds and inlines the lib', () => {
    const dir = makeFixture({ withMarker: true });
    const result = runBuild(dir);
    assert.equal(result.status, 0, result.stderr);
    const generated = fs.readFileSync(path.join(dir, 'user.js', 'demo.user.js'), 'utf-8');
    assert.match(generated, /function dbg\(\) \{\}/, 'the lib must actually be inlined');
    assert.match(generated, />>> GENERATED by/, 'and wrapped in the generated banner');
  });

  await t.test('a source missing its marker fails the build', () => {
    const dir = makeFixture({ withMarker: false });
    const result = runBuild(dir);
    assert.notEqual(result.status, 0, 'a lost marker must not build clean');
    assert.match(result.stderr, /no \/\* @include <name> \*\/ marker found/);
    assert.match(result.stderr, /demo\.src\.js/, 'the error must name the offending file');
    assert.equal(
      fs.existsSync(path.join(dir, 'user.js', 'demo.user.js')),
      false,
      'and must not leave a generated file behind',
    );
  });

  await t.test('the marker guard is reported distinctly from a version problem', () => {
    // Both guards run over the same sources. A fixture that trips one must not
    // be diagnosed as the other -- the marker error names the include, the
    // parity error names the manifest.
    const dir = makeFixture({ withMarker: false });
    const result = runBuild(dir);
    assert.doesNotMatch(result.stderr, /@version/);
  });
});
