#!/usr/bin/env python3
"""Generate distributable .user.js files from .src.js sources.

Each userscript's *.src.js source contains an `/* @include <name> */` marker
where a shared fragment from user.js/lib/<name> should be inlined. This keeps
helpers that are identical across scripts (retry/backoff request wrapper,
gated debug logging) defined exactly once, while the generated *.user.js
files stay fully self-contained -- Tampermonkey loads a single file per
script, with no runtime @require dependency.

Usage:
    python user.js/scripts/build_userscripts.py           # regenerate all
    python user.js/scripts/build_userscripts.py --check    # verify up to date, no writes
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

USERSCRIPTS_DIR = pathlib.Path('user.js')
LIB_DIR = USERSCRIPTS_DIR / 'lib'
INCLUDE_RE = re.compile(r'^([ \t]*)/\*\s*@include\s+(\S+)\s*\*/[ \t]*$', re.MULTILINE)
VERSION_RE = re.compile(r'^//\s*@version\s+(\S+)\s*$', re.MULTILINE)

GENERATED_BANNER = (
    '// >>> GENERATED by user.js/scripts/build_userscripts.py from {name} + lib/{lib} <<<\n'
    '// >>> Do not hand-edit the block below; edit the source and regenerate. <<<\n'
)
GENERATED_FOOTER = '// >>> END GENERATED BLOCK <<<\n'


def render(src_path: pathlib.Path) -> str:
    """Expand every `/* @include <name> */` marker in `src_path` with the
    matching user.js/lib/<name> fragment, wrapped in a generated-block
    banner so hand-edits are visibly out of place."""
    text = src_path.read_text(encoding='utf-8')

    def _replace(match: re.Match) -> str:
        indent, lib_name = match.group(1), match.group(2)
        lib_path = LIB_DIR / lib_name
        if not lib_path.exists():
            raise FileNotFoundError(f'{src_path}: no such lib file {lib_path}')
        fragment = lib_path.read_text(encoding='utf-8')
        banner = GENERATED_BANNER.format(name=src_path.name, lib=lib_name)
        block = banner + fragment.rstrip('\n') + '\n' + GENERATED_FOOTER
        return '\n'.join(indent + line if line else line for line in block.splitlines())

    return INCLUDE_RE.sub(_replace, text)


def header_block(path: pathlib.Path) -> str:
    """Return a userscript's ==UserScript== metadata block, or the whole file
    when no terminator is present.

    Directives are only meaningful inside that block, and scanning the whole
    file would let an unrelated line elsewhere in ~11,600 lines of JavaScript
    masquerade as one.
    """
    text = path.read_text(encoding='utf-8')
    end = text.find('// ==/UserScript==')
    return text if end == -1 else text[:end]


def check_version_parity(src_path: pathlib.Path) -> str | None:
    """Compare the `@version` in a .src.js userscript header against the one in
    its sibling .meta.js update manifest.

    Tampermonkey polls the .meta.js to decide whether an update exists, but
    installs the .user.js generated from the .src.js -- so when the two disagree
    the update check and the shipped code are describing different versions.
    AGENTS.md asks a human to bump both; this turns that into an invariant the
    build enforces.

    Note the two files indent the header value differently
    (`// @version      2.0.225` vs `// @version         1.7.9`), so match on
    VERSION_RE rather than a fixed-width slice.

    Returns None when the pair agrees, or a message describing the problem when
    it does not.
    """
    meta_path = src_path.with_name(src_path.name.replace('.src.js', '.meta.js'))
    if not meta_path.exists():
        # Hard error, not a silent skip. Tampermonkey polls the .meta.js to
        # discover updates, so a script shipping without one never auto-updates
        # -- and merging to master is this repo's deploy. A skip would also make
        # the check cover less than it appears to, which is exactly the kind of
        # claim docs/CONCERNS.md had to walk back elsewhere.
        return (
            f'{src_path.name}: no sibling {meta_path.name}. Tampermonkey polls the '
            f'.meta.js to discover updates, so this script would never auto-update. '
            f'Add the manifest, or remove the source.'
        )

    found = {}
    for path in (src_path, meta_path):
        # Search the metadata block only. A .src.js is ~11,600 lines of
        # JavaScript, and a stray `// @version ...` in a comment further down
        # would otherwise be a candidate match.
        header = header_block(path)
        match = VERSION_RE.search(header)
        if match is None:
            return (
                f'{path.name}: no `// @version <value>` line in its ==UserScript== '
                f'block. Nothing to compare against {"the manifest" if path is src_path else "the source"}.'
            )
        found[path] = match.group(1)

    if found[src_path] != found[meta_path]:
        return (
            f'@version mismatch: {src_path.name} says {found[src_path]}, '
            f'{meta_path.name} says {found[meta_path]}. Bump both to the same value '
            f'(see AGENTS.md); Tampermonkey checks one file and installs the other.'
        )
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Verify generated files are up to date; do not write.')
    args = parser.parse_args()

    src_files = sorted(USERSCRIPTS_DIR.glob('*.src.js'))
    if not src_files:
        print(f'No .src.js files found in {USERSCRIPTS_DIR}', file=sys.stderr)
        return 1

    stale = []
    version_problems = []
    for src_path in src_files:
        # Checked on every run, not just --check: a mismatch is worth surfacing
        # while regenerating too, and it is collected rather than raised so one
        # run reports every bad pair instead of only the first.
        problem = check_version_parity(src_path)
        if problem:
            version_problems.append(problem)

        out_path = src_path.with_name(src_path.name.replace('.src.js', '.user.js'))
        rendered = render(src_path)
        current = out_path.read_text(encoding='utf-8') if out_path.exists() else None
        if rendered == current:
            print(f'up to date: {out_path.name}')
            continue
        if args.check:
            stale.append(out_path.name)
            continue
        out_path.write_text(rendered, encoding='utf-8', newline='\n')
        print(f'wrote: {out_path.name}')

    if version_problems:
        for problem in version_problems:
            print(problem, file=sys.stderr)
        return 1

    if args.check and stale:
        print(f'Stale generated file(s): {", ".join(stale)}. Run without --check to regenerate.', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
