#!/usr/bin/env python3
"""Generate distributable .user.js files from .src.js sources.

Each userscript's *.src.js source contains an `/* @include <name> */` marker
where a shared fragment from user.js/lib/<name> should be inlined. This keeps
helpers that are identical across scripts (retry/backoff request wrapper,
gated debug logging) defined exactly once, while the generated *.user.js
files stay fully self-contained -- Tampermonkey loads a single file per
script, with no runtime @require dependency.

Usage:
    python user.js/scripts/build_userscripts.py           # regenerate all
    python user.js/scripts/build_userscripts.py --check    # verify up to date, no writes
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

USERSCRIPTS_DIR = pathlib.Path('user.js')
LIB_DIR = USERSCRIPTS_DIR / 'lib'
INCLUDE_RE = re.compile(r'^([ \t]*)/\*\s*@include\s+(\S+)\s*\*/[ \t]*$', re.MULTILINE)

GENERATED_BANNER = (
    '// >>> GENERATED by user.js/scripts/build_userscripts.py from {name} + lib/{lib} <<<\n'
    '// >>> Do not hand-edit the block below; edit the source and regenerate. <<<\n'
)
GENERATED_FOOTER = '// >>> END GENERATED BLOCK <<<\n'


def render(src_path: pathlib.Path) -> str:
    """Expand every `/* @include <name> */` marker in `src_path` with the
    matching user.js/lib/<name> fragment, wrapped in a generated-block
    banner so hand-edits are visibly out of place."""
    text = src_path.read_text(encoding='utf-8')

    def _replace(match: re.Match) -> str:
        indent, lib_name = match.group(1), match.group(2)
        lib_path = LIB_DIR / lib_name
        if not lib_path.exists():
            raise FileNotFoundError(f'{src_path}: no such lib file {lib_path}')
        fragment = lib_path.read_text(encoding='utf-8')
        banner = GENERATED_BANNER.format(name=src_path.name, lib=lib_name)
        block = banner + fragment.rstrip('\n') + '\n' + GENERATED_FOOTER
        return '\n'.join(indent + line if line else line for line in block.splitlines())

    return INCLUDE_RE.sub(_replace, text)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Verify generated files are up to date; do not write.')
    args = parser.parse_args()

    src_files = sorted(USERSCRIPTS_DIR.glob('*.src.js'))
    if not src_files:
        print(f'No .src.js files found in {USERSCRIPTS_DIR}', file=sys.stderr)
        return 1

    stale = []
    for src_path in src_files:
        out_path = src_path.with_name(src_path.name.replace('.src.js', '.user.js'))
        rendered = render(src_path)
        current = out_path.read_text(encoding='utf-8') if out_path.exists() else None
        if rendered == current:
            print(f'up to date: {out_path.name}')
            continue
        if args.check:
            stale.append(out_path.name)
            continue
        out_path.write_text(rendered, encoding='utf-8', newline='\n')
        print(f'wrote: {out_path.name}')

    if args.check and stale:
        print(f'Stale generated file(s): {", ".join(stale)}. Run without --check to regenerate.', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
